# Copyright 2020 Google, LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Maha-Alpha Deploy

on:
  push:
    tags:
    - v*-alpha

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment:
      name: alpha
      url: 'http://35.188.244.130:4000' ##use the one generated on deployment
    env:
      GCE_INSTANCE: ${{ secrets.GCE_INSTANCE }}
      GCE_INSTANCE_ZONE: us-east4-c


    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker

    # Build the Docker image
    # the `GITHUB_REF` will fetch the tag ref responsible for triggering the action.
    # using `${GITHUB_REF##*/}` gets the tag used i.e v0.8.7-alpha. Check the link for more information
    # https://stackoverflow.com/questions/9532654/expression-after-last-specific-character
    - name: Build
      run: |
        echo '${{ secrets.RELEASES_SECRETS }}' >> config/releases.exs
        docker build --tag "gcr.io/duncan-openc2-plugfest/twinklymaha:${GITHUB_REF_NAME}" .

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/duncan-openc2-plugfest/twinklymaha:${GITHUB_REF_NAME}"

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        service: twinklymaha-alpha
        region: us-east-4
        image: "gcr.io/duncan-openc2-plugfest/twinklymaha:${{ github.ref_name }}"

