on:
  release:
    types: 
      - published

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: ['1.14.5']
        otp: ['25.3.2.2']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-type: loose
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.13.0
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          curl -L -o cyclonedx-cli https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.22.0/cyclonedx-linux-x64
          chmod a+x cyclonedx-cli
           make sbom
      - name: Upload SBOM Json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./twinkly_maha.*-cyclonedx-sbom.1.0.0.json
          asset_name: twinkly_maha.*-cyclonedx-sbom.1.0.0.json
          asset_content_type: application/octet-stream
      - name: Upload SBOM XML
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./twinkly_maha.*-cyclonedx-sbom.1.0.0.xml
          asset_name: twinkly_maha.*-cyclonedx-sbom.1.0.0.xml
          asset_content_type: application/octet-stream

      - name: Upload SBOM SPDX
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./twinkly_maha.*-cyclonedx-sbom.1.0.0.spdx
          asset_name: twinkly_maha.*-cyclonedx-sbom.1.0.0.spdx
          asset_content_type: application/octet-stream
